name: GitHub Actions

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    Build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: '6.0'
            - name: Install dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --configuration Release --no-restore
            - name: Install browsers
              run: pwsh PlaywrightFramework/bin/Release/net6.0/playwright.ps1 install
            - name: Test
              run: dotnet test --no-restore --verbosity normal --logger trx
            - name: Test Report
              uses: dorny/test-reporter@v1
              if: success() || failure()
              with:
                name: Tests
                path: PlaywrightFramework/TestResults/*.trx
                reporter: dotnet-trx
                fail-on-error: 'false'
